### ISSUE TITLE
artisan db:seed fails to complete

### ISSUE THREAD

**Issue by LDShadowLord** [booklib-org/Booklib#4]
Not experienced with PHP, so unsure what the issue is or if this is a misconfiguration on my end.
The two preceding artisan commands completed succesfully.
Running MariaDB with a user with "Grant All" privileges on a database specifically for booklib.
Installing on Alpine Linux 3.14 inside a Docker container. All commands are being run as ROOT.

> Seeding: Database\Seeders\setting_thumbnail
> Seeded:  Database\Seeders\setting_thumbnail (8.48ms)
> Seeding: Database\Seeders\scanning_frequency
> Seeded:  Database\Seeders\scanning_frequency (0.52ms)
> 
>    Illuminate\Contracts\Container\BindingResolutionException 
> 
>   Target class [Database\Seeders\create_admin_user] does not exist.
> 
>   at /Booklib/vendor/laravel/framework/src/Illuminate/Container/Container.php:875
>     871▕ 
>     872▕         try {
>     873▕             $reflector = new ReflectionClass($concrete);
>     874▕         } catch (ReflectionException $e) {
>   ➜ 875▕             throw new BindingResolutionException("Target class [$concrete] does not exist.", 0, $e);
>     876▕         }
>     877▕ 
>     878▕         // If the type is not instantiable, the developer is attempting to resolve
>     879▕         // an abstract type such as an Interface or Abstract Class and there is
> 
>       +8 vendor frames 
>   9   /Booklib/database/seeders/DatabaseSeeder.php:18
>       Illuminate\Database\Seeder::call()
> 
>       +22 vendor frames 
>   32  /Booklib/artisan:37
>       Illuminate\Foundation\Console\Kernel::handle()

**Comment by MKaterbarg** [comment]
This appear to be an issue due to the merged pull request #3  in which a seeder class was removed, but is still being executed.

**Comment by MKaterbarg** [comment]
This issue is now resolved. Please update your code base using "git pull" in the main directory, and it should work fine.
